### ISSUE TITLE
ITSx on reverse-complement

### ISSUE THREAD

**Issue by wzacs1** [USDA-ARS-GBRU/itsxpress#11]
Hi,
First, thanks for this useful tool and the qiime2 plugin as well!
It seems from my testing that the ITSx implementation here does not also search reverse-complement of input, as ITSx originally did by default.  Is this correct, and if so, would it be possible to implement a flag to search the other orientation?  
It seems reasonable to not do both as ITSx defaults did, for reasons of speed. However, In our case, we sequence ITS2, but read 1 is obtained from the downstream/28S side and read2 is primed off the upstream / 5.8S side. This was done to try to get the best quality sequence from the slightly more information-rich side.  I find that though itsxpress can pair our reads nicely, it fails to find any ITS sequences and extract them (though primers are on there as well).  However, if I pair outside of itsxpress, then reverse-complement and put the paired reads through as single-end reads, it finds ITS2 subregion in majority of the reads nicely.  Also, running directly in ITSx works fine, so I am left believing there is no orientation check in itsxpress, but cannot tell for sure. Is this correct?

Thanks.

**Comment by arivers** [comment]
It wasn't a speed issue so much as I couldn't think of a use case for reverse complementing. Most people use the [standard ITS primer sets](https://unite.ut.ee/primers.php) and those are all in the forward orientation. 

I should be able to implement this option, but I'll need to do some testing on the parsing functions to make sure it trims everything correctly in the different output modes. Is this a method you see other groups using or are there any papers you could point me to for this?

**Comment by wzacs1** [comment]
Yes, we actually did take these primers and the orientation from a Taylor, et. al 2016 _AEM_ paper and I believe these primers are increasingly in use and likely to continue (IMHO of course), though one does not have to do this orientation to use the primers described. I should have included this reference initially. They did this orientation to reduce hairpin formation with Illumina adapters, but I also find the length of useful sequence post-ITSx extraction to be much less from the 5.8S /reverse side, which turns out to be fortuitous on occasions when the Illumina read 2 quality really tanks towards the end. Here is the reference:

[](https://aem.asm.org/content/82/24/7217)

Thanks for considering this.  I'm happy to provide test sequences if you like.  Let me know.

**Comment by arivers** [comment]
Thanks.  Coincidentally, of the Qiime developers had this same issue with a dataset he selected for a tutorial he's developing.  I'll try to add it for your all.

Would it be best to return the trimmed sequences to you in their original orientation but trimmed? 
I can also return them to you in the reverse-complemented orientation.

Would any of your data sets ever have samples where some needed to be reverse complemented and others did not?

**Comment by arivers** [comment]
added in 1.8.0
