### ISSUE TITLE
Conda install not compatible with QIIME2 2019.10

### ISSUE THREAD

**Issue by ppericard** [USDA-ARS-GBRU/itsxpress#16]
Hi,
Right now it seems that ITSxpress (1.7.2 and 1.8.0) is not compatible with QIIME2 2019.10 when installing both through conda (https://data.qiime2.org/distro/core/qiime2-2019.10-py36-linux-conda.yml).
The incompatibility rises from HMMER version specification between ITSxpress and SEPP (qiime2 2019.10 dependancy):

```
UnsatisfiableError: The following specifications were found to be in conflict:
  - itsxpress=1.7.2 -> hmmer[version='>=3.1']
  - sepp=4.3.10 -> hmmer==3.1b2
```

In conda versioning, v3.1b is strictly inferior to v3.1 which leads to a conflict.
Would it be possible to lower ITSxpress bioconda specification of HMMER version to `>=3.1b` in order to make it compatible with QIIME2 latest version?

Thanks in advance,
Pierre

**Comment by arivers** [comment]
There should be no issue with downgrading it other than I just released the new 1.8.0 this morning on conda :(

I see you contacted SEPP too.  Should I hold off until we see what they say?

**Comment by ppericard** [comment]
@arivers, yep just saw your update... Timing sucks...
We definitely can wait a bit to see what the SEPP team response will be. It would make more sense for them to relax the HMMER version if they can.
But then, we would need to make sure either the SEPP bioconda recipe is updated at the same version, or that qiime2-2019.10 update their dependencies to make ITSxpress compatible with them again...

**Comment by arivers** [comment]
my travicCI build uses 3.1b2 without issue.  I could also change my dependencies to hmmer>= 3.1b2

Hmmer versioning is goes 3.0, 3.1b1, 3.2b2, 3.2, 3.2.1

**Comment by ppericard** [comment]
So, it seems that it is gonna be difficult to change the HMMER dependency of the SEPP bioconda recipe.
I'm wondering if you can just change the recipe in bioconda without having to change the version of ITSxpress ?

**Comment by arivers** [comment]
I'll do that.

**Comment by arivers** [comment]
I submitted a pull request to updatethe  itsxpress bioconda recipe:

https://github.com/bioconda/bioconda-recipes/pull/19282
