### ISSUE TITLE
itsxpress produces empty files after merging

### ISSUE THREAD

**Issue by mfbeuq** [USDA-ARS-GBRU/itsxpress#17]
Hey guys,

thanks for making this plugin. I'm̀ currently trying to get this plugin to work for the first time with my first fungal data set. I have demultiplexed my dataset and tried itsxpress both in qiime2 and as standalone and both in paired and single read mode but I always get empty read files even though I am getting sequences while the program runs:

e.g. when working with single end reads 
7964852 nt in 32803 seqs, min 65, max 246, avg 243
minseqlength 32: 3 sequences discarded.
Sorting 100%
16376 unique sequences, avg cluster 2.0, median 1, max 3949
Writing output file 100%
Writing uc file, first part 100%
Writing uc file, second part 100%

and with paired-end reads:
Writing mergable reads merged.
Started output threads.
Total time: 1.139 seconds.

Pairs:               	42110
Joined:              	27279   	64.780%
Ambiguous:           	4403       	10.456%
No Solution:         	10428   	24.764%
Too Short:           	0       	0.000%

Avg Insert:          	278.6
Standard Deviation:  	31.9
Mode:                	266

Insert range:        	73 - 458
90th percentile:     	321
75th percentile:     	285
50th percentile:     	267
25th percentile:     	265
10th percentile:     	258

I tried both the new version 1.8.0 and 1.7.2 and both produces the same empty read files:

my commands are as followed in the standalone version:
###paired reads
for i in *L001_R*.fastq.gz ;do
    varID=$(echo $i | grep -o -a "^S[[:digit:]]*"  )
    echo "processing $varID \n"
    itsxpress --fastq "$varID"_"$varID"_L001_R1_001.fastq.gz --fastq2 "$varID"_"$varID"_L001_R2_001.fastq.gz --region ALL \
--taxa Fungi --log logfile.txt --outfile itsxpress/"$varID"_trimmed_reads.fastq.gz --threads 10
done

###single reads
for i in *L001_R*.fastq.gz ;do
    varID=$(echo $i | grep -o -a "^S[[:digit:]]*"  )
    echo "processing $varID \n"
    itsxpress --fastq "$varID"_"$varID"_L001_R1_001.fastq.gz --single_end --region ALL \
--taxa Fungi --log logfile.txt --outfile itsxpress/"$varID"_trimmed_reads.fastq.gz --threads 10
done

Any help? :) Thanks 

Cheers, Max

**Comment by arivers** [comment]
I think this is happening because you are using all as the it's region when you should select its1 or its2 as the region.

**Comment by mfbeuq** [comment]
Yeah its working fine now, thanks!! Im still having some problems though but Ill try to figure them out myself for now!
