### ISSUE TITLE
ITSxpress not working with reverse complimented reads

### ISSUE THREAD

**Issue by DGladish** [USDA-ARS-GBRU/itsxpress#19]
Hello!

I have some reverse compliment single end fungal ITS1 reads obtained via IonTorrent sequencing that I am trying to use ITSxpress on to extract the ITS1 region. When I run ITSxpress, a fastq with no text is produced. I tried incorporating --reversed_primers to account for this, but I get the same result, a fastq file with no text in it. 

Does anyone have a solution for this?

**Comment by arivers** [comment]
can you include any error messages, and are you running itsxpress within Qiime or stand-alone? What primer set are you using?  --reverse-primers if for primer sets where the Forward primer is downstream and the reverse primer is upstream of the target site.    I've not encountered reveres complemented reads I didn't think. 

Have you tried reversing them, complimenting them, or reverse complementing them with a tool like bbtools reformat.sh?

**Comment by DGladish** [comment]
I installed ITSxpress in a qiime2-2021.4 conda environment using the instructions indicated here: https://github.com/USDA-ARS-GBRU/itsxpress-tutorial/blob/master/ITSxpress-tutorial.md. We are using primer set ITS1 and ITS2.

Has it been reported that simply reverse complimenting the sequences would allow ITSxpress to function correctly? I have read on a QIIME2 forum that this should work in theory, but presents issues such as described here: https://forum.qiime2.org/t/itsxpress-does-not-extract-sequences-where-itsx-does/10799/5. It seems that this is an issue when working with paired end data. Would this still be an issue for single-end?

**Comment by DGladish** [comment]
Update: I have used a tool my colleague developed to reverse compliment the sequences (tool available here: https://github.com/duceppemo/QIIME2_ITS/blob/master/fastq_rc.py) and then tested ITSxpress. It seems to have functioned properly. I will provide any updates as to whether or not I run any issues while passing the data through the QIIME2 pipeline.

**Comment by DGladish** [comment]
Hello! Reverse-complimenting the reads seemed to do the trick. I was able to successfully use ITSxpress on the reads after doing so, and then run the files through the QIIME2 pipeline.
