### ISSUE TITLE
Running ITSxpress in parallel

### ISSUE THREAD

**Issue by LukeLikesDirt** [USDA-ARS-GBRU/itsxpress#26]
Hi

Are you able to run ITSxpress in parallel? I can't figure this one out. The best I could do are the two codes below, but ITSxpress doesn't recognise the comand.

```
parallel -j 4 'itsxpress \
	--fastq cutadapt/*.fq.gz \
	--single_end \
	--region ALL \
	--taxa Fungi \
	--log itsxpress/logfile/{/.}_ITS-ALL.txt \
	--outfile itsxpress/{/.}_ITS-ALL.fq.gz {}' \
	::: cutadapt/*.fq.gz
```
itsxpress: error: unrecognized arguments: cutadapt/S063.fq.gz cutadapt/S064.fq.gz cutadapt/S066.fq.gz ...and so on.

```
parallel -j 4 'itsxpress \
	--fastq .fq.gz \
	--single_end \
	--region ALL \
	--taxa Fungi \
	--log itsxpress/logfile/{/.}_ITS-ALL.txt \
	--outfile itsxpress/{/.}_ITS-ALL.fq.gz {}' \
	::: --fastq cutadapt/*.fq.gz
```
itsxpress: error: unrecognized arguments: cutadapt/S063.fq.gz...and so on.

Cheers
Luke

**Comment by arivers** [comment]
I've run it in parallel using Slurm, but not GNU parallel. This looks like an issue in what parallel is passing to ITSxpress.
