### ISSUE TITLE
Cannot properly install on qiime2

### ISSUE THREAD

**Issue by yoshinak1** [USDA-ARS-GBRU/itsxpress#28]
Hi, I just installed itsxpress to my qiime2 environment and got some error.
When I install with “conda install -c bioconda itsxpress” , itsxpress was not associated with conda command and “qiime itsxpress” returns “Error: QIIME 2 has no plugin/command named 'itsxpress'.”
Just hit “itsxpress” returuns some message
~$ itsxpress
usage: itsxpress [-h] --fastq FASTQ [--single_end] [--fastq2 FASTQ2] –outfile…
So, it seems something is wrong with conda installation.
I tried qiime2-2021.11 and 2021.8, my conda version is 4.13.0.
With pip installation, I can successfully install the itsxpress.

**Comment by gabrielet** [comment]
@yoshinak1 you said that:
 ```
Just hit “itsxpress” returuns some message
~$ itsxpress
usage: itsxpress [-h] --fastq FASTQ [--single_end] [--fastq2 FASTQ2] –outfile…
```
i believe it means that ITSxpress is installed and working.

You can also try these two commands. If they work you will be able to use ITSxpress.

```
itsxpress --help
qiime itsxpress --version
```

They should be probably run withing the QIIME2 environment you created when installing QIIME2, i.e. maybe you need to activate it with something like `conda activate qiime2-2022.8` or the corresponding QIIME2 version.

**Comment by yoshinak1** [comment]
@gabrielet Thanks for the reply.
Since, it was some time ago, I almost forgot what was happened at that time.
In my situation, with "conda" installation itsxpress was not associated with conda properly and could not run any command, but with "pip" installation itsxpress was working fine. But I did not want to mix up "pip" and "conda" installation on a same environment at that time. That's the reason why I asked you some advice.
I'm still using pip installed itsxpress and haven’t seen any issue in my conda environment.
Anyway, Thanks for the advice!
