### ISSUE TITLE
Trimming primers before running ITS xpress

### ISSUE THREAD

**Issue by dalofa** [USDA-ARS-GBRU/itsxpress#40]
Hi

I am working on some single-ended PacBio data. The following to things are unclear to me:
1. Is it necessary to trim the primers from the circular consensus reads before running ITS xpress
2. Should I check if reads classified as not having the full region contains either ITS1 or ITS2

Thanks a ton for the help (in advance)!

**Comment by seina001** [comment]
Hello,

1. No that is not necessary, trimming the primers off may cause issues with ITSxpress trim. 
2. No you can classify them as ITS1/2 or full region. However, I haven't worked with PacBio data before using ITSxpress.
What format/scale are the quality scores on your reads? Would you be willing to share a subset (couple hundred reads) of your PacBio data? I'd like to test for PacBio compatibility, and test question 2 properly.

**Comment by dalofa** [comment]
1. Thank you.
2. I am working with files found in the following bioproject: PRJNA952168. An example could be: [SRX19870078](https://www.ncbi.nlm.nih.gov/sra/SRX19870078[accn])

**Comment by Robvh-git** [comment]
@seina001 you specify that trimming of primers may cause issues with ITSxpress, but does ITSxpress then assumes that a standard set of primers is used?

**Comment by Robvh-git** [comment]
@seina001 thank you for the info and makes sense. The primers I use are outside of the ITS region (end 18S and beginning of 28S), so I decided now to not trim the primers, as itsxpress trims everything before and after the ITS region anyway.
