### ISSUE TITLE
clustering behavior of itsxpress

### ISSUE THREAD

**Issue by Robvh-git** [USDA-ARS-GBRU/itsxpress#41]
Hello,

in `itsxpress` it is possible to cluster using the `--cluster_id` parameter, and if I'm not mistaken, it uses vsearch for this.

However, in the output files, I cannot seem to find the number of reads that were inside of a cluster? You will lose the majority of reads in this way? Also, are the centroids or consensus sequences in the output?

Will clustering occur if `--cluster_id` is not stated? In the `itsxpress --help` output, there is no default value specified. 

Perhaps I'm missing something very obvious.

Thanks!

**Comment by seina001** [comment]
The output of itsxpress is trimming the original reads based on the centroid that was passed to hmmsearch, so you don't lose any reads. The original reads are trimmed to start and stop points from the centroid read output from hmmsearch. The clustering method is to only search the hmm profiles once for a given read.

You can pass the flag --keeptemp which will give you the files you're looking for, if you still want to take a look at them. 

Yes the default clustering is set to 1.0

**Comment by Robvh-git** [comment]
@seina001 okay so if I understand it correctly, the clustering with vsearch does not deliver output of vsearch? This clustering is just an intermediate step, and - even if cluster_id = 0.99 - you will end up with original reads?

What I do notice, is that if I specify a cluster_id <1.0, there are empty read entries in the output file. This is not the case if cluster_id=1.0. What causes this?

**Comment by arivers** [comment]
@seina001 can you check if you can replicate empty read entries in Version 2.0.2?  I think it may not do this now.
