### ISSUE TITLE
using ITSxpress with nanopore sequencing reads - error profile

### ISSUE THREAD

**Issue by Robvh-git** [USDA-ARS-GBRU/itsxpress#45]
Hello,

I'm using ITSxpress in combination with Nanopore sequencing reads, and find that only 4-6% of the sequenced reads are annotated as ITS reads. 

We are having some issues with the PCR, so it could well be that only a small fraction of the amplicons are indeed ITS.

However, it could laso be that the relative large error rate of nanopore sequencing could be the culprit. Is ITSxpress compatible with the error profile of Nanopore reads?

Thanks.

**Comment by arivers** [comment]
We have not evaluated ITSxpress for nanopore reads, but I'm happy to look at it.   Could you share the primers, taxa, and command you ran along with any output?  Did you run it in Qiime or stand-alone?  Could you share example data either publically or privately so we can test too?

**Comment by Robvh-git** [comment]
@arivers thank you for the quick reply. I ran following command:
`itsxpress --fastq filtered_barcode01.fastq --keeptemp --single_end --outfile ITS_selected.fastq --region ALL --threads 24`

primers are: ITS9MUNngs (TACACACCGCCCGTCG) + ITS4ngsUni (CCTSCSCTTANTDATATGC) that were tailed with ONT barcodes.

The input fastq data was pre-filtered based on following parameters: min length = 300, max length = 1800, min quality = 12.

You can find the `filtered_barcode01.fastq` file on the following WeTransfer link: https://we.tl/t-lh0nqxm4eX . If you prefer to receive the example data in another way, please let me know. The original sample is rhizosphere soil from a greenhouse experiment containing 70% sterile silversand and 30% argicultural field soil.
