### ISSUE TITLE
Retain untrimmed reads

### ISSUE THREAD

**Issue by LukeLikesDirt** [USDA-ARS-GBRU/itsxpress#50]
Hello

I am running ITSxpress on forward reads only because my forward and reverse reads cannot be merged. Because I expect to lose taxa with an ITS region > 180bp, I want to retrieve the untrimmed reads so I can identify the taxa that are being lost. Is there an option to retrieve untrimmed reads (I can't see one in the documentation)?

Cheers
Luke

**Comment by arivers** [comment]
Can you compare the FASTQ headers of your forward input reads to the FASTQ headers of the trimmed reads output by ITSxpress and use those to get the untrimmed reads?

**Comment by LukeLikesDirt** [comment]
Yes, I could do that. But what I am in fact after is to be able to retain reads with the forward conserved part removed (i.e. SSU bit for ITS1 or 5.8S bit for ITS2) when using ITSxpress on forward reads only. This option is available on ITSx and would be a nice addition to ITSxpress. 

Have you considered allowing read to be retained when only one end of the ITS is trimmed? 

Regards
Luke

**Comment by LukeLikesDirt** [comment]
Hi Adam

Thank you for your thoughtful reply. If I were to use DADA2 on partially trimmed ITS1 reads (i.e., assessing ITS1 forward reads only where the SSU part was trimmed but not the 5.8S part, meaning the fraction of reads belonging to fungi with a long ITS1), I would later cluster the reads into OTUs to address intraspecific variation in the ITS. I’m unsure why these partially trimmed ITS reads would inflate diversity (could you please elaborate?), but I wonder if clustering post-denoising would address the issue.

Kind regards
Luke
